# Site settings
title: Mugricio
email: mugricio@protonmail.com
description: > 
  La página preferida del Presidente de la Nación, Ing. Ladricio Lacri. Macri Gato.
baseurl: "" 
url: "http://www.mugricio.com" 
permalink: /:title.html
excerpt_separator: <!--more-->
paginate: 6
paginate_path: "/page:num/"
timezone: America/Argentina/Buenos_Aires
markdown: kramdown
